import { useState } from "react";

const Add = () =>{
    // three states to manage my two inputs and id to be generated
    
    const [name,setName] = useState("");//name input
    const [price,setPrice] = useState("")// price input
    const [id,setId] = useState(Date.now())// id been generated by us

    const handleformsubmission = (event) =>{
        event.preventDefault();
        
       

    }




    return(
        <div className="row justify-content-center pb-5">
            <div className="col-md-8 pb-5">
               <div className="row">
                    <div className="col">
                        <h1 className="text-center"> Add shopping cart</h1>
                    </div>
                </div> 
               
            </div>
            <div className="row">
                <div className="col-">
                    <form className="bg-primary p-4" onSubmit={handleformsubmission}>
                        <div className="row">
                            <div className="col-md-6">
                                <input type="text" className="form-control" placeholder="product Name" value={name}
                                 onChange={(event)=>{
                                    setName(event.target.value )
                                 }} />
                            </div>
                            <div className="col-md-3">
                                <input type="text" className="form-control" placeholder="price" value={price} onChange={(event)=>{
                                    setPrice(event.target.value)
                                }}
                                />
                            </div>
                            <div className="col-md-3">
                                <input type="submit" className="btn btn-success" value="Add to list"/>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    )
}
export default Add;